apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certName }}
  namespace: {{ .Values.certManager.namespace | default "default" }} 
spec:
  secretName: {{ .Values.certManager.secretName }}
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: ClusterIssuer
  commonName: {{ .Values.certManager.domain }}
  dnsNames:
    - {{ .Values.certManager.domain }}
  duration: {{ .Values.certManager.duration | default "2160h" }}
  renewBefore: {{ .Values.certManager.renewBefore | default "720h" }}
