{{- if .Values.sttWorkerHPA.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stt-wkr-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stt-wkr-deploy
  minReplicas: {{ .Values.sttWorkerHPA.minReplicas }}
  maxReplicas: {{ .Values.sttWorkerHPA.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sttWorkerHPA.targetCPUUtilizationPercentage }}
{{- end }}