grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  defaultDatasourceEnabled: false  # 사실상 커스텀이라 디폴트끔

  sidecar:
    datasources:
      enabled: false # 수동 datasource 쓸 거니까 끔
    dashboards:
      enabled: true # 기본 제공 대시보드만 자동 등록
      searchNamespace: ALL

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-operated.default.svc.cluster.local:9090
          isDefault: true
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.default.svc.cluster.local:3100
          isDefault: false

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    additionalServiceMonitors:
      - name: fastapi-monitor
        selector:
          matchLabels:
            app: fastapi
        namespaceSelector:
          matchNames:
            - default
        endpoints:
          - port: http
            path: /metrics