loki:
  enabled: true

grafana:
  enabled: false    

prometheus:
  enabled: false  

promtail:
  enabled: true    
  config:
    snippets:
      pipelineStages:
        - cri: {}
      extraScrapeConfigs: |
        - job_name: fastapi-logs
          static_configs:
            - targets:
                - localhost
              labels:
                job: fastapi
                __path__: /var/log/containers/*fastapi*.log
